project:
  type: book
  output-dir: docs
  
book:
  title: VALORIZE
  author: Meliana - Oktober 2025
  repo-url: https://github.com/uwdata/visualization-curriculum
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook]
  chapters:
    - index.md
    - part: Curriculum
      chapters:
        - valorize_introduction.ipynb
        - valorize_content1.ipynb
        - valorize_content2.ipynb
    - part: Support
      chapters:
        - valorize_support.ipynb

format:
  html:
    theme: cosmo

