project:
  type: book
  output-dir: docs
  
book:
  title: VALORIZE
  author: Tim Penelitian - 2025
  repo-url: https://github.com/uwdata/visualization-curriculum
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook]
  chapters:
    - index.md
    - part: Konsep
      chapters:
        - valorize_introduction.ipynb
        - valorize_buktiempiris1.ipynb
        - valorize_content1.ipynb
    - part: Research Outputs
      chapters:
        - valorize_publikasi.ipynb
    - part: Lampiran
      chapters:
        - valorize_lampiranbuktiempiris1.ipynb
        - valorize_lampirankementrian.ipynb
    - part: Acknowledgement
      chapters:
        - valorize_support.ipynb

format:
  html:
    theme: cosmo

